name: "app-network"

version: 1.0.0

client:
  organization: Org1
  logging:
    level: info
  cryptoconfig:
    path: ${GOPATH}/src/github.com/hyperledger/fabric-chaincode-test/network/crypto-config
  credentialStore:
    path: /tmp/app-store
    cryptoStore:
      path: /tmp/app-msp
  BCCSP:
    security:
      enabled: true
      default:
        provider: "SW"
      hashAlgorithm: "SHA2"
      softVerify: true
      level: 256
  tlsCerts:
    systemCertPool: true
    client:
      key:
        path: ${GOPATH}/src/github.com/hyperledger/fabric-chaincode-test/network/crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/tls/client.key
      cert:
        path: ${GOPATH}/src/github.com/hyperledger/fabric-chaincode-test/network/crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/tls/client.crt

channels:
  mychannel:
    peers:
      peer0.org1.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer1.org1.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer0.org2.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer1.org2.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

    policies:
      queryChannelConfig:
        minResponses: 1
        maxTargets: 1
        retryOpts:
          attempts: 5
          initialBackoff: 500ms
          maxBackoff: 5s
          backoffFactor: 2.0
      discovery:
        maxTargets: 2
        retryOpts:
          attempts: 4
          initialBackoff: 500ms
          maxBackoff: 5s
          backoffFactor: 2.0
      eventService:
        resolverStrategy: PreferOrg
        balancer: Random
        blockHeightLagThreshold: 5
        reconnectBlockHeightLagThreshold: 10
        peerMonitorPeriod: 5s

organizations:
  Org1:
    mspid: Org1MSP
    cryptoPath: peerOrganizations/org1.example.com/users/{userName}@org1.example.com/msp
    peers:
      - peer0.org1.example.com
      - peer1.org1.example.com
    certificateAuthorities:
      - ca.org1.example.com

  Org2:
    mspid: Org2MSP
    cryptoPath: peerOrganizations/org2.example.com/users/{userName}@org2.example.com/msp
    peers:
      - peer0.org2.example.com
      - peer1.org2.example.com
    certificateAuthorities:
      - ca.org2.example.com

  OrdererOrg:
    mspid: OrdererMSP
    cryptoPath: ordererOrganizations/example.com/users/{username}@example.com/msp
    orderers:
      - orderer.example.com
      # - orderer1.example.com
      # - orderer2.example.com
      # - orderer3.example.com
      # - orderer4.example.com

orderers:
  orderer.example.com:
    url: grpcs://localhost:7050
    grpcOptions:
      ssl-target-name-override: orderer.example.com
      allow-insecure: false
      
    tlsCACerts:
      path: ${GOPATH}/src/github.com/hyperledger/fabric-chaincode-test/network/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem

  orderer1.example.com:
    url: grpcs://localhost:8050
    grpcOptions:
      ssl-target-name-override: orderer1.example.com
      allow-insecure: false
    tlsCACerts:
      path: ${GOPATH}/src/github.com/hyperledger/fabric-chaincode-test/network/crypto-config/ordererOrganizations/example.com/orderers/orderer2.example.com/msp/tlscacerts/tlsca.example.com-cert.pem

  orderer2.example.com:
    url: grpcs://localhost:9050
    grpcOptions:
      ssl-target-name-override: orderer2.example.com
      allow-insecure: false
    tlsCACerts:
      path: ${GOPATH}/src/github.com/hyperledger/fabric-chaincode-test/network/crypto-config/ordererOrganizations/example.com/orderers/orderer3.example.com/msp/tlscacerts/tlsca.example.com-cert.pem

  orderer3.example.com:
    url: grpcs://localhost:10050
    grpcOptions:
      ssl-target-name-override: orderer3.example.com
      allow-insecure: false
    tlsCACerts:
      path: ${GOPATH}/src/github.com/hyperledger/fabric-chaincode-test/network/crypto-config/ordererOrganizations/example.com/orderers/orderer4.example.com/msp/tlscacerts/tlsca.example.com-cert.pem

  orderer4.example.com:
    url: grpcs://localhost:11050
    grpcOptions:
      ssl-target-name-override: orderer4.example.com
      allow-insecure: false
    tlsCACerts:
      path: ${GOPATH}/src/github.com/hyperledger/fabric-chaincode-test/network/crypto-config/ordererOrganizations/example.com/orderers/orderer5.example.com/msp/tlscacerts/tlsca.example.com-cert.pem

peers:
  peer0.org1.example.com:
    url: grpcs://localhost:7051
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      allow-insecure: false
    tlsCACerts:
      path: ${GOPATH}/src/github.com/hyperledger/fabric-chaincode-test/network/crypto-config/peerOrganizations/org1.example.com/tlsca/tlsca.org1.example.com-cert.pem

  peer1.org1.example.com:
    url: grpcs://localhost:8051
    grpcOptions:
      ssl-target-name-override: peer1.org1.example.com
      allow-insecure: false
    tlsCACerts:
      path: ${GOPATH}/src/github.com/hyperledger/fabric-chaincode-test/network/crypto-config/peerOrganizations/org1.example.com/tlsca/tlsca.org1.example.com-cert.pem

  peer0.org2.example.com:
    url: grpcs://localhost:9051
    grpcOptions:
      ssl-target-name-override: peer0.org2.example.com
      allow-insecure: false
    tlsCACerts:
      path: ${GOPATH}/src/github.com/hyperledger/fabric-chaincode-test/network/crypto-config/peerOrganizations/org2.example.com/tlsca/tlsca.org2.example.com-cert.pem

  peer1.org2.example.com:
    url: grpcs://localhost:10051
    grpcOptions:
      ssl-target-name-override: peer1.org2.example.com
      allow-insecure: false
    tlsCACerts:
      path: ${GOPATH}/src/github.com/hyperledger/fabric-chaincode-test/network/crypto-config/peerOrganizations/org2.example.com/tlsca/tlsca.org2.example.com-cert.pem


certificateAuthorities:
  ca.org1.example.com:
    url: grpcs://http://localhost:7054
    tlsCACerts:
      path: ${GOPATH}/src/github.com/hyperledger/fabric-chaincode-test/network/crypto-config/peerOrganizations/org1.example.com/ca/ca.org1.example.com-cert.pem
    registrar:
      enrollId: admin
      enrollSecret: adminpw
    caName: ca.org1.example.com

  ca.org2.example.com:
    url: grpcs://http://localhost:8054
    tlsCACerts:
      path: ${GOPATH}/src/github.com/hyperledger/fabric-chaincode-test/network/crypto-config/peerOrganizations/org2.example.com/ca/ca.org2.example.com-cert.pem
    registrar:
      enrollId: admin
      enrollSecret: adminpw
    caName: ca.org2.example.com


entityMatchers:
  peer:
    - pattern: (\w*)peer0.org1.example.com(\w*)
      urlSubstitutionExp: grpcs://localhost:7051
      sslTargetOverrideUrlSubstitutionExp: peer0.org1.example.com
      mappedHost: peer0.org1.example.com

    - pattern: (\w*)peer1.org1.example.com(\w*)
      urlSubstitutionExp: grpcs://localhost:8051
      sslTargetOverrideUrlSubstitutionExp: peer1.org1.example.com
      mappedHost: peer1.org1.example.com

    - pattern: (\w*)peer0.org2.example.com(\w*)
      urlSubstitutionExp: grpcs://localhost:9051
      sslTargetOverrideUrlSubstitutionExp: peer0.org2.example.com
      mappedHost: peer0.org2.example.com

    - pattern: (\w*)peer1.org2.example.com(\w*)
      urlSubstitutionExp: grpcs://localhost:10051
      sslTargetOverrideUrlSubstitutionExp: peer1.org2.example.com
      mappedHost: peer1.org2.example.com

  orderer:
    - pattern: (\w*)orderer.example.com(\w*)
      urlSubstitutionExp: localhost:7050
      sslTargetOverrideUrlSubstitutionExp: orderer.example.com
      mappedHost: orderer.example.com

    - pattern: (\w*)orderer1.example.com(\w*)
      urlSubstitutionExp: localhost:8050
      sslTargetOverrideUrlSubstitutionExp: orderer1.example.com
      mappedHost: orderer1.example.com

    - pattern: (\w*)orderer2.example.com(\w*)
      urlSubstitutionExp: localhost:9050
      sslTargetOverrideUrlSubstitutionExp: orderer2.example.com
      mappedHost: orderer2.example.com

    - pattern: (\w*)orderer3.example.com(\w*)
      urlSubstitutionExp: localhost:10050
      sslTargetOverrideUrlSubstitutionExp: orderer3.example.com
      mappedHost: orderer3.example.com

    - pattern: (\w*)orderer4.example.com(\w*)
      urlSubstitutionExp: localhost:11050
      sslTargetOverrideUrlSubstitutionExp: orderer4.example.com
      mappedHost: orderer4.example.com

  certificateAuthorities:
    - pattern: (\w*)ca.org1.example.com(\w*)
      urlSubstitutionExp: http://localhost:7054
      mappedHost: ca.org1.example.com

    - pattern: (\w*)ca.org2.example.com(\w*)
      urlSubstitutionExp: http://localhost:8054
      mappedHost: ca.org2.example.com
